name: Approval test flow
on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo building
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
     - uses: trstringer/manual-approval@v1
       with:
        secret: ${{ github.TOKEN }}
        approvers: MagicTeam
        minimum-approvals: 1
        issue-title: "Deploying v1.3.5 to prod from staging"
        issue-body: "Please approve or deny the deployment of version v1.3.5."
     - name: Deploy to production
       run: echo deploying
