name: Consume Artifact

on: workflow_dispatch

jobs:
  consume:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        run_id: 6009554154