name: Copy Flow

on:
  workflow_dispatch:

env:
  SOURCE_FOLDER: "C:/DeploymentFiles/VersionFolder"
  DESTINATION_FOLDER: "C:/DeploymentFiles/ReleaseFolder"

jobs:
  generate-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run your build steps here
      # ...
      # Create a folder and five files
      - name: Create Folder and Files
        run: |
          mkdir my-folder
          for i in {1..5}; do
            echo "This is the content of file ${i}" > "my-folder/file${i}.txt"
          done

      # Publish the folder as an artifact
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-folder-artifact
          path: my-folder

  Copy-file-git-lighsail:
    name: Copy File
    needs: generate-artifact
    if: success()  
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Create Folder abc
      run: mkdir abc

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: my-folder-artifact
        path: ./abc
      # Create a folder named "abc"

    - name: cd files
      run: |
        ls -R ./abc
      # Zip the contents of the "abc" folder
    - name: Zip Artifact
      run: zip -r my-folder-artifact.zip abc/*
    - name: cd files
      run: |
        ls


    - name: Install sshpass dependency for ssh access
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Create ~/.ssh directory for storing known hosts
      run: mkdir -p ~/.ssh

    - name: Update known_hosts file with the server ip to avoid fingerprint ask
      run: |
        WINDOWS_SERVER_IP="${{ secrets.REMOTE_HOSTGC }}"
        echo "$WINDOWS_SERVER_IP $(ssh-keyscan -t rsa $WINDOWS_SERVER_IP 2>&1)" >> ~/.ssh/known_hosts

    - name: copy the latest files at C drive
      run: |
        sshpass -vvv -p "${{ secrets.REMOTE_PASSWORDGC }}" scp -o StrictHostKeyChecking=no "${{ github.workspace }}/my-folder-artifact.zip" "${{ secrets.REMOTE_ADMINGC }}"@"${{ secrets.REMOTE_HOSTGC }}":"${{ env.SOURCE_FOLDER }}"

  # Stop-IIS:
  #   name: Stop-IIS 
  #   needs: Copy-file-git-lighsail
  #   runs-on: ubuntu-latest
  #   if: success() 
  #   steps:
  #     - uses: actions/checkout@v3.0.0
        
  #     - run: |
  #         # Replace the placeholders with actual values
  #         WINDOWS_SERVER_USER="Administrator"
  #         WINDOWS_SERVER_IP="3.110.130.37"
  #         REM_FOLDER="C:/test2"
  #         sshpass -vvv -p 'akqR3XeigseYHlWxD$T8ZtpWu&T*BkJm' ssh -o StrictHostKeyChecking=no "$WINDOWS_SERVER_USER@$WINDOWS_SERVER_IP" "powershell -Command \"Stop-Service -Name W3SVC; Get-Service -Name W3SVC\""
 
  # Remove-old-files:
  #   name: Remove-old-files-from-intepub-location
  #   needs: Stop-IIS
  #   runs-on: ubuntu-latest
  #   if: success() 
  #   steps:
  #     - uses: actions/checkout@v3.0.0
        
  #     - run: |
  #         # Replace the placeholders with actual values
  #         WINDOWS_SERVER_USER="Administrator"
  #         WINDOWS_SERVER_IP="3.110.130.37"
  #         REM_FOLDER="C:/test2"
  #         sshpass -vvv -p 'akqR3XeigseYHlWxD$T8ZtpWu&T*BkJm' ssh -o StrictHostKeyChecking=no "$WINDOWS_SERVER_USER@$WINDOWS_SERVER_IP" "powershell -Command \"Get-ChildItem -Path '$REM_FOLDER' -File | Where-Object { \$_.Name -ne 'config.txt' } | Remove-Item -Force\""

  # Copy-new-files:
  #   name: copy-new-files-to-intepub-location
  #   needs: Remove-old-files
  #   runs-on: ubuntu-latest
  #   if: success() 
  #   steps:
  #     - uses: actions/checkout@v3.0.0
        
  #     - run: |
  #         # Replace the placeholders with actual values
  #         WINDOWS_SERVER_USER="Administrator"
  #         WINDOWS_SERVER_IP="3.110.130.37"
  #         SOURCE_FOLDER="C:/test3"
  #         DESTINATION_FOLDER="C:/test2/"
  #         sshpass -vvv -p 'akqR3XeigseYHlWxD$T8ZtpWu&T*BkJm' ssh -o StrictHostKeyChecking=no "$WINDOWS_SERVER_USER@$WINDOWS_SERVER_IP" "powershell -Command \"\$latestFile = Get-ChildItem -Path '$SOURCE_FOLDER' | Sort-Object LastWriteTime -Descending | Select-Object -First 1; Copy-Item -Path \$latestFile.FullName -Destination '$DESTINATION_FOLDER'\""

  # Start-IIS:
  #   name: Start-IIS
  #   needs: Copy-new-files
  #   runs-on: ubuntu-latest
  #   if: success() 
  #   steps:
  #     - uses: actions/checkout@v3.0.0
        
  #     - run: |
  #         # Replace the placeholders with actual values
  #         WINDOWS_SERVER_USER="Administrator"
  #         WINDOWS_SERVER_IP="3.110.130.37"
  #         sshpass -vvv -p 'akqR3XeigseYHlWxD$T8ZtpWu&T*BkJm' ssh -o StrictHostKeyChecking=no "$WINDOWS_SERVER_USER@$WINDOWS_SERVER_IP" "powershell -Command \"Start-Service -Name W3SVC; Get-Service -Name W3SVC\""
