name: Build and Publish .NET Code

on:
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Change this to your desired .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build .NET code
      run: dotnet build --configuration Release

    - name: Publish .NET code
      run: dotnet publish --configuration Release --output ./publish

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-code-artifact
        path: ./publish
